# Libraries:
library(ggplot2)
library(gganimate)

# Creating the monthly dataframes

x_03=data.frame(Industry=c('Travel', 'Automotive','Pets',                                           'Jewelry','Apparel')
                    , GMV_YoY=c(215.2, 250.82, 19.00, 35, 38)
                    , months=rep('March 2020',5))


x_04=data.frame(Industry=c('Travel', 'Automotive','Pets',                                           'Jewelry','Apparel')
                    , GMV_YoY=c(32, -94, 10.28, -23, 33)
                    , months=rep('April 2020',5))
                    
x_bind=rbind(x_03,x_04)

index <- rep(1:2,each=5)
           
df_x <- data.frame(index,x_bind[, 1],x_bind[, 2],x_bind[, 3])

df_x
names(df_x) <- c("index", "Industry", "Gross_Merchandise_Volume_YoY", "Month")

df_x

```{r}

a <- ggplot(df_x, aes(x = Industry,y = Gross_Merchandise_Volume_YoY, fill = Industry)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(" ", values = c("Apparel" = "#91b8bd", "Automotive" = "#acc8d4", "Jewelry" = "#336666","Pets" = "#efe8d1","Travel" = "#fbb042")) +
  labs(title = "Industry Losers in GMV Growth Year-Over-Year due to COVID-19",
  subtitle = "{closest_state}",
  y = "Gross Merchandise Volume Year-Over-Year, %") +
  geom_text(aes(label = as.character(Gross_Merchandise_Volume_YoY), y = Gross_Merchandise_Volume_YoY), vjust = 0.6, hjust = -0.9) +
  coord_flip(clip = "on", expand = TRUE) +
  theme(axis.text.x = element_text(face = "bold", size = 18),
  axis.text.y = element_text(face = "bold", size = 18),
  plot.title = element_text(size=24),
  plot.subtitle = element_text(size=18),
  axis.title = element_text(face = "bold", size = 18),
  legend.position = "none",
  legend.text=element_text(size=16),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black")) +
  transition_states(Month, transition_length = 6, state_length = 6) + 
  enter_fade() + 
  exit_shrink() +
  ease_aes("cubic-in-out")

animate(a, duration = 12, fps = 20, width = 1200, height = 600, renderer = gifski_renderer())

anim_save("GMV_Losers.gif")

plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

